[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_sola = "13QsVLZkzf9gRiFbFrUK9xhLa6QukFEdLxJUfbuta33L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/cupnfish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
