[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_sola = "13QsVLZkzf9gRiFbFrUK9xhLa6QukFEdLxJUfbuta33L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/cupnfish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/mpl-token-metadata/programs/.bin/token_metadata.so"
